In [1]:
import requests as req
import pandas as pd
import numpy as np
from pandas import DataFrame

In [2]:
#datainfo = https://bitcoincharts.com/charts/bitstampUSD#rg10zig5-minzczsg2019-06-17zeg2019-06-29ztgSzm1g10zm2g25zi1gRSIzv
#No tiene el exchange que busco, pero es lo unico que he encontrado que me facilite la info en min5.
data = pd.read_csv('BTCPrice.csv', engine = 'python', delimiter=";", decimal=",")
#display(data.head())
#display(data.shape)

**Separo timestamp en fecha y min5**

In [3]:
def SplitTime (df):  
    return [i.split() for i in df['Timestamp']] 
    
def TimeDate (df, col1, col2):
    date=[]
    time=[]
    for t in SplitTime(df):
        date.append(t[0])r
        time.append(t[1])
    df[col1]=date
    df[col2]=time
    return df


display(TimeDate(data, 'Date', '5min').head())


"""
EXPlicacion

def TimeDate (df, col1, col2):
display(TimeDate(data, 'Date', '5min')

df = data
col1 = Date
col2 = 5min

"""

,Timestamp,Open,High,Low,Close,Volume (BTC),Volume (Currency),Weighted Price,Date,5min
0,2019-06-03 00:00:00,8735.84,8745.96,8715.67,8715.74,15.77,137608.69,8724.77,2019-06-03,00:00:00
1,2019-06-03 00:05:00,8715.74,8718.09,8691.93,8706.82,58.71,511301.42,8709.02,2019-06-03,00:05:00
2,2019-06-03 00:10:00,8706.76,8708.93,8685,8685,54.75,476283.04,8699.47,2019-06-03,00:10:00
3,2019-06-03 00:15:00,8686.16,8696,8671.47,8676.82,68.32,593057.25,8680.62,2019-06-03,00:15:00
4,2019-06-03 00:20:00,8677.79,8695.56,8676.28,8691.24,11.44,99289.49,8682.81,2019-06-03,00:20:00

"\nEXPlicacion\n\ndef TimeDate (df, col1, col2):\ndisplay(TimeDate(data, 'Date', '5min')\n\ndf = data\ncol1 = Date\ncol2 = 5min\n\n"

**Elimino la columna de 'Timestamp'**

In [4]:
def colsDropper(df, col):
    return df.drop([col], axis = 1, inplace = True)

colsDropper(data, 'Timestamp')
data.head()

,Open,High,Low,Close,Volume (BTC),Volume (Currency),Weighted Price,Date,5min
0,8735.84,8745.96,8715.67,8715.74,15.77,137608.69,8724.77,2019-06-03,00:00:00
1,8715.74,8718.09,8691.93,8706.82,58.71,511301.42,8709.02,2019-06-03,00:05:00
2,8706.76,8708.93,8685,8685,54.75,476283.04,8699.47,2019-06-03,00:10:00
3,8686.16,8696,8671.47,8676.82,68.32,593057.25,8680.62,2019-06-03,00:15:00
4,8677.79,8695.56,8676.28,8691.24,11.44,99289.49,8682.81,2019-06-03,00:20:00

In [5]:
#times = [i.split() for i in data['Timestamp']]

#date = []
#time = []
#for i in times:
#    date.append(i[0])
#    time.append(i[1])

#data_clean = data.drop(['Timestamp'], axis=1)
#data_clean.insert(0, "Date", date, False) 
#data_clean.insert(1, '5min', time, False)

In [6]:
def Replace(df):
    a = df.replace('—', 0, inplace=True)
    return a
Replace(data)

def FixShit(col):
    data[col] = data[col].astype(float)
    return  data[col]

FixShit('Open')
FixShit('Low')
FixShit('High')
FixShit('Volume (BTC)')
FixShit('Volume (Currency)')
FixShit('Weighted Price')
FixShit('Close')
print(data.dtypes)
data.head()

Open                 float64
High                 float64
Low                  float64
Close                float64
Volume (BTC)         float64
Volume (Currency)    float64
Weighted Price       float64
Date                  object
5min                  object
dtype: object

,Open,High,Low,Close,Volume (BTC),Volume (Currency),Weighted Price,Date,5min
0,8735.84,8745.96,8715.67,8715.74,15.77,137608.69,8724.77,2019-06-03,00:00:00
1,8715.74,8718.09,8691.93,8706.82,58.71,511301.42,8709.02,2019-06-03,00:05:00
2,8706.76,8708.93,8685.00,8685.00,54.75,476283.04,8699.47,2019-06-03,00:10:00
3,8686.16,8696.00,8671.47,8676.82,68.32,593057.25,8680.62,2019-06-03,00:15:00
4,8677.79,8695.56,8676.28,8691.24,11.44,99289.49,8682.81,2019-06-03,00:20:00

In [7]:
#data['Open'].replace('—', 0, inplace=True)
#data['Close'].replace('—', 0, inplace=True)

In [8]:


def resta(df, Open, Close, Diff):
    df[Diff] = df[Open]-df[Close]
    return df

display(resta(data, 'Open','Close', 'Diff').head())



"""
El mercado es mas manipulable cuando el BTC vale menos vs. es menos manipulable porque el inversor tiene mas BTC acum
por tema wykoff. 

Medir mechas tras movimientos fuertes. Detectar long/short close - high/low.

"""

,Open,High,Low,Close,Volume (BTC),Volume (Currency),Weighted Price,Date,5min,Diff
0,8735.84,8745.96,8715.67,8715.74,15.77,137608.69,8724.77,2019-06-03,00:00:00,20.10
1,8715.74,8718.09,8691.93,8706.82,58.71,511301.42,8709.02,2019-06-03,00:05:00,8.92
2,8706.76,8708.93,8685.00,8685.00,54.75,476283.04,8699.47,2019-06-03,00:10:00,21.76
3,8686.16,8696.00,8671.47,8676.82,68.32,593057.25,8680.62,2019-06-03,00:15:00,9.34
4,8677.79,8695.56,8676.28,8691.24,11.44,99289.49,8682.81,2019-06-03,00:20:00,-13.45

'\nEl mercado es mas manipulable cuando el BTC vale menos vs. es menos manipulable porque el inversor tiene mas BTC acum\npor tema wykoff. \n\nMedir mechas tras movimientos fuertes. Detectar long/short close - high/low.\n\n'

In [9]:
FixShit('Diff')
print(data.dtypes)

Open                 float64
High                 float64
Low                  float64
Close                float64
Volume (BTC)         float64
Volume (Currency)    float64
Weighted Price       float64
Date                  object
5min                  object
Diff                 float64
dtype: object

Finding out the position type (long vs.short)

In [10]:
def position(df, Diff, Position):
    
    lst=[]  
    for pos in df[Diff]:
        if pos > 0:
            lst.append('long')
        elif pos == 0:
            lst.append('no mov')
        else:
            lst.append('short')
    df[Position]=lst
    return df

display(position(data, 'Diff', 'Position').head())

,Open,High,Low,Close,Volume (BTC),Volume (Currency),Weighted Price,Date,5min,Diff,Position
0,8735.84,8745.96,8715.67,8715.74,15.77,137608.69,8724.77,2019-06-03,00:00:00,20.10,long
1,8715.74,8718.09,8691.93,8706.82,58.71,511301.42,8709.02,2019-06-03,00:05:00,8.92,long
2,8706.76,8708.93,8685.00,8685.00,54.75,476283.04,8699.47,2019-06-03,00:10:00,21.76,long
3,8686.16,8696.00,8671.47,8676.82,68.32,593057.25,8680.62,2019-06-03,00:15:00,9.34,long
4,8677.79,8695.56,8676.28,8691.24,11.44,99289.49,8682.81,2019-06-03,00:20:00,-13.45,short

Setting absolute values in diff

In [50]:
def absolute(df, Diff, Open, Close):
    df[Diff] = abs(df[Open]-df[Close])
    return df

def movesize(df, Close, Open):
    df['MoveSize (%)']= abs(round(((df[Open]-df[Close])/df[Open])*100, 2))
    return df
display(movesize(data, 'Open', 'Close').head())

,Open,High,Low,Close,Volume (BTC),Volume (Currency),Weighted Price,Date,5min,Diff,Position,MoveSize (%)
0,8735.84,8745.96,8715.67,8715.74,15.77,137608.69,8724.77,2019-06-03,00:00:00,20.10,long,0.23
1,8715.74,8718.09,8691.93,8706.82,58.71,511301.42,8709.02,2019-06-03,00:05:00,8.92,long,0.10
2,8706.76,8708.93,8685.00,8685.00,54.75,476283.04,8699.47,2019-06-03,00:10:00,21.76,long,0.25
3,8686.16,8696.00,8671.47,8676.82,68.32,593057.25,8680.62,2019-06-03,00:15:00,9.34,long,0.11
4,8677.79,8695.56,8676.28,8691.24,11.44,99289.49,8682.81,2019-06-03,00:20:00,-13.45,short,0.15

API

In [51]:
import json
import requests
from datetime import datetime

**Uso de la api: cuando detecto que hay un operador en el mercado, le doy a run para ir viendo el movimiento del precio. **

In [52]:
res = requests.get('https://www.bitstamp.net/api/ticker_hour/')
dev=res.json()

def TimeConverter (dev):
    Timestamp = int(dev.get('timestamp'))
    time_conversion = str(datetime.fromtimestamp(Timestamp))
    date_split = time_conversion.split()
    date=[date_split[0]]
    time=[date_split[1]]
    
    return date, time

display(TimeConverter(dev))

(['2019-07-01'], ['16:22:57'])

In [53]:
def GetBtc(df):

    lst = [*dev.values()]
    date, time = TimeConverter(dev)
    Open = [lst[8]]
    High = [lst[0]]
    Low = [lst[6]]
    Close = [lst[1]]
    VolumeBTC = [lst[5]]
    Weighted_Price = [lst[4]]
    
    return date, time, Open, High, Low, Close, VolumeBTC, Weighted_Price

display(GetBtc(data))

#Be careful with the volume for the 24h and the one I have is for 5 min.

(['2019-07-01'],
 ['16:22:57'],
 [10759.24],
 ['10669.79000000'],
 ['10456.00000000'],
 ['10609.65'],
 ['923.48518766'],
 ['10568.49'])

Nueva columna diferencia de Px de apertura con el Px de cierre (hay que meterlo en otro archivo de funciones)

**Analisis**

In [54]:
display(data.head())

,Open,High,Low,Close,Volume (BTC),Volume (Currency),Weighted Price,Date,5min,Diff,Position,MoveSize (%)
0,8735.84,8745.96,8715.67,8715.74,15.77,137608.69,8724.77,2019-06-03,00:00:00,20.10,long,0.23
1,8715.74,8718.09,8691.93,8706.82,58.71,511301.42,8709.02,2019-06-03,00:05:00,8.92,long,0.10
2,8706.76,8708.93,8685.00,8685.00,54.75,476283.04,8699.47,2019-06-03,00:10:00,21.76,long,0.25
3,8686.16,8696.00,8671.47,8676.82,68.32,593057.25,8680.62,2019-06-03,00:15:00,9.34,long,0.11
4,8677.79,8695.56,8676.28,8691.24,11.44,99289.49,8682.81,2019-06-03,00:20:00,-13.45,short,0.15

In [57]:
big_sizes = data.sort_values(['MoveSize (%)', 'Date', '5min'], ascending = False)
display(big_sizes.head())

,Open,High,Low,Close,Volume (BTC),Volume (Currency),Weighted Price,Date,5min,Diff,Position,MoveSize (%)
6872,12818.98,12900.00,11942.24,11954.34,1070.85,13082516.44,12216.94,2019-06-26,20:40:00,864.64,long,7.23
6871,13443.07,13445.15,12711.46,12818.98,638.47,8322604.63,13035.26,2019-06-26,20:35:00,624.09,long,4.87
6873,11942.24,12574.07,11853.12,12524.96,1348.67,16456123.45,12201.76,2019-06-26,20:45:00,-582.72,short,4.65
6878,12394.79,12400.00,11853.12,11946.73,642.82,7782859.78,12107.30,2019-06-26,21:10:00,448.06,long,3.75
5646,11045.33,11056.80,10619.89,10650.50,359.95,3910536.13,10864.23,2019-06-22,14:30:00,394.83,long,3.71