In [1]:
import requests as req
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
from pandas import DataFrame

In [2]:
#datainfo = https://bitcoincharts.com/charts/bitstampUSD#rg10zig5-minzczsg2019-06-17zeg2019-06-29ztgSzm1g10zm2g25zi1gRSIzv
#No tiene el exchange que busco, pero es lo unico que he encontrado que me facilite la info en min5.
data = pd.read_csv('BTCPrice.csv', engine = 'python', delimiter=";", decimal=",")
#display(data.head())
#display(data.shape)

**Separo timestamp en fecha y min5**

In [3]:
def SplitTime (df):  
    return [i.split() for i in df['Timestamp']] 
    
def TimeDate (df, col1, col2):
    date=[]
    time=[]
    for t in SplitTime(df):
        date.append(t[0])
        time.append(t[1])
    df[col1]=date
    df[col2]=time
    return df


display(TimeDate(data, 'Date', '5min').head())


"""
EXPlicacion

def TimeDate (df, col1, col2):
display(TimeDate(data, 'Date', '5min')

df = data
col1 = Date
col2 = 5min

"""

,Timestamp,Open,High,Low,Close,Volume (BTC),Volume (Currency),Weighted Price,Date,5min
0,2019-06-03 00:00:00,8735.84,8745.96,8715.67,8715.74,15.77,137608.69,8724.77,2019-06-03,00:00:00
1,2019-06-03 00:05:00,8715.74,8718.09,8691.93,8706.82,58.71,511301.42,8709.02,2019-06-03,00:05:00
2,2019-06-03 00:10:00,8706.76,8708.93,8685,8685,54.75,476283.04,8699.47,2019-06-03,00:10:00
3,2019-06-03 00:15:00,8686.16,8696,8671.47,8676.82,68.32,593057.25,8680.62,2019-06-03,00:15:00
4,2019-06-03 00:20:00,8677.79,8695.56,8676.28,8691.24,11.44,99289.49,8682.81,2019-06-03,00:20:00

"\nEXPlicacion\n\ndef TimeDate (df, col1, col2):\ndisplay(TimeDate(data, 'Date', '5min')\n\ndf = data\ncol1 = Date\ncol2 = 5min\n\n"

**Elimino la columna de 'Timestamp'**

In [4]:
def colsDropper(df, col):
    return df.drop([col], axis = 1, inplace = True)

colsDropper(data, 'Timestamp')
data.head()

,Open,High,Low,Close,Volume (BTC),Volume (Currency),Weighted Price,Date,5min
0,8735.84,8745.96,8715.67,8715.74,15.77,137608.69,8724.77,2019-06-03,00:00:00
1,8715.74,8718.09,8691.93,8706.82,58.71,511301.42,8709.02,2019-06-03,00:05:00
2,8706.76,8708.93,8685,8685,54.75,476283.04,8699.47,2019-06-03,00:10:00
3,8686.16,8696,8671.47,8676.82,68.32,593057.25,8680.62,2019-06-03,00:15:00
4,8677.79,8695.56,8676.28,8691.24,11.44,99289.49,8682.81,2019-06-03,00:20:00

In [5]:
#times = [i.split() for i in data['Timestamp']]

#date = []
#time = []
#for i in times:
#    date.append(i[0])
#    time.append(i[1])

#data_clean = data.drop(['Timestamp'], axis=1)
#data_clean.insert(0, "Date", date, False) 
#data_clean.insert(1, '5min', time, False)

In [6]:
def Replace(df):
    a = df.replace('—', 0, inplace=True)
    return a
Replace(data)

def FixShit(col):
    data[col] = data[col].astype(float)
    return  data[col]

FixShit('Open')
FixShit('Low')
FixShit('High')
FixShit('Volume (BTC)')
FixShit('Volume (Currency)')
FixShit('Weighted Price')
FixShit('Close')
print(data.dtypes)
data.head()

Open                 float64
High                 float64
Low                  float64
Close                float64
Volume (BTC)         float64
Volume (Currency)    float64
Weighted Price       float64
Date                  object
5min                  object
dtype: object

,Open,High,Low,Close,Volume (BTC),Volume (Currency),Weighted Price,Date,5min
0,8735.84,8745.96,8715.67,8715.74,15.77,137608.69,8724.77,2019-06-03,00:00:00
1,8715.74,8718.09,8691.93,8706.82,58.71,511301.42,8709.02,2019-06-03,00:05:00
2,8706.76,8708.93,8685.00,8685.00,54.75,476283.04,8699.47,2019-06-03,00:10:00
3,8686.16,8696.00,8671.47,8676.82,68.32,593057.25,8680.62,2019-06-03,00:15:00
4,8677.79,8695.56,8676.28,8691.24,11.44,99289.49,8682.81,2019-06-03,00:20:00

In [7]:
#data['Open'].replace('—', 0, inplace=True)
#data['Close'].replace('—', 0, inplace=True)

In [8]:
import numpy as np

def resta(df, Open, Close, Diff):
    df[Diff] = df[Open]-df[Close]
    return df

display(resta(data, 'Open','Close', 'Diff').head())



"""
El mercado es mas manipulable cuando el BTC vale menos vs. es menos manipulable porque el inversor tiene mas BTC acum
por tema wykoff. 

Medir mechas tras movimientos fuertes. Detectar long/short close - high/low.

"""

,Open,High,Low,Close,Volume (BTC),Volume (Currency),Weighted Price,Date,5min,Diff
0,8735.84,8745.96,8715.67,8715.74,15.77,137608.69,8724.77,2019-06-03,00:00:00,20.10
1,8715.74,8718.09,8691.93,8706.82,58.71,511301.42,8709.02,2019-06-03,00:05:00,8.92
2,8706.76,8708.93,8685.00,8685.00,54.75,476283.04,8699.47,2019-06-03,00:10:00,21.76
3,8686.16,8696.00,8671.47,8676.82,68.32,593057.25,8680.62,2019-06-03,00:15:00,9.34
4,8677.79,8695.56,8676.28,8691.24,11.44,99289.49,8682.81,2019-06-03,00:20:00,-13.45

'\nEl mercado es mas manipulable cuando el BTC vale menos vs. es menos manipulable porque el inversor tiene mas BTC acum\npor tema wykoff. \n\nMedir mechas tras movimientos fuertes. Detectar long/short close - high/low.\n\n'

In [9]:
FixShit('Diff')
print(data.dtypes)

Open                 float64
High                 float64
Low                  float64
Close                float64
Volume (BTC)         float64
Volume (Currency)    float64
Weighted Price       float64
Date                  object
5min                  object
Diff                 float64
dtype: object

Finding out the position type (long vs.short)

In [10]:
def position(df, Diff, Position):
    
    lst=[]  
    for pos in df[Diff]:
        if pos > 0:
            lst.append('long')
        elif pos == 0:
            lst.append('no mov')
        else:
            lst.append('short')
    df[Position]=lst
    return df

display(position(data, 'Diff', 'Position').head())

,Open,High,Low,Close,Volume (BTC),Volume (Currency),Weighted Price,Date,5min,Diff,Position
0,8735.84,8745.96,8715.67,8715.74,15.77,137608.69,8724.77,2019-06-03,00:00:00,20.10,long
1,8715.74,8718.09,8691.93,8706.82,58.71,511301.42,8709.02,2019-06-03,00:05:00,8.92,long
2,8706.76,8708.93,8685.00,8685.00,54.75,476283.04,8699.47,2019-06-03,00:10:00,21.76,long
3,8686.16,8696.00,8671.47,8676.82,68.32,593057.25,8680.62,2019-06-03,00:15:00,9.34,long
4,8677.79,8695.56,8676.28,8691.24,11.44,99289.49,8682.81,2019-06-03,00:20:00,-13.45,short

Setting absolute values in diff

In [11]:
def absolute(df, Diff, Open, Close):
    df[Diff] = abs(df[Open]-df[Close])
    return df

display(absolute(data,'Diff','Open','Close').head())





#!!!!!!!!! Calcular el % de movimiento: (Open-Close/Open)

,Open,High,Low,Close,Volume (BTC),Volume (Currency),Weighted Price,Date,5min,Diff,Position
0,8735.84,8745.96,8715.67,8715.74,15.77,137608.69,8724.77,2019-06-03,00:00:00,20.10,long
1,8715.74,8718.09,8691.93,8706.82,58.71,511301.42,8709.02,2019-06-03,00:05:00,8.92,long
2,8706.76,8708.93,8685.00,8685.00,54.75,476283.04,8699.47,2019-06-03,00:10:00,21.76,long
3,8686.16,8696.00,8671.47,8676.82,68.32,593057.25,8680.62,2019-06-03,00:15:00,9.34,long
4,8677.79,8695.56,8676.28,8691.24,11.44,99289.49,8682.81,2019-06-03,00:20:00,13.45,short

API

In [12]:
import json
import requests

In [13]:
res = requests.get('https://www.bitstamp.net/api/ticker_hour/')
dev=res.json()
print(dev)
lst = [*dev.values()]
print(lst)

{'high': '11118.08000000', 'last': '11108.00', 'timestamp': '1561912608', 'bid': '11108.00', 'vwap': '10931.74', 'volume': '1026.07623292', 'low': '10813.23000000', 'ask': '11108.07', 'open': 11867.35}
['11118.08000000', '11108.00', '1561912608', '11108.00', '10931.74', '1026.07623292', '10813.23000000', '11108.07', 11867.35]

In [14]:
from datetime import datetime

lst_api = [*dev.values()]
timestamp = int(lst[2])
dt_object = str(datetime.fromtimestamp(timestamp))

#date_time_list = dt_object.split()
#print(date_time_list)

In [15]:
def GetBtc(df, timestamp, Open, High, Low, Close, VolumeBTC, Weighted_Price):
    res = requests.get('https://www.bitstamp.net/api/ticker_hour/')
    dev = res.json()
    lst = [*dev.values()]
    df[timestamp] =[lst[2]]
    df[Open] = [lst[8]]
    df[High] = [lst[0]]
    df[Low] = [lst[6]]
    df[Close] = [lst[1]]
    df[VolumeBTC] = [lst[5]]
    df[Weighted_Price] = [lst[4]]
    return 

display(GetBtc(data))

#it is giving me the volume for the 24h and the one I have is for 5 min.

TypeError: GetBtc() missing 7 required positional arguments: 'timestamp', 'Open', 'High', 'Low', 'Close', 'VolumeBTC', and 'Weighted_Price'

In [35]:
#tests
"""
"""

def position(df, Diff, Position):
    
    lst=[]  
    for pos in df[Diff]:
        if pos > 0:
            lst.append('long')
        elif pos == 0:
            lst.append('no mov')
        else:
            lst.append('short')
    df[Position]=lst
    return df
display(position(data, 'Diff', 'Position').head())

11590.00000000

In [49]:
#tests

res = requests.get('https://www.bitstamp.net/api/ticker_hour/')
dev=res.json()
lst = [*dev.values()]
Open = [lst[8]]

print(Open)

[11867.35]

In [33]:
data_api = dev.items()
print(data_api)

for key in dev.keys():
    print(key)

dict_items([('high', '11590.00000000'), ('last', '11095.94'), ('timestamp', '1561903344'), ('bid', '11097.56'), ('vwap', '11196.9'), ('volume', '1251.24548426'), ('low', '10966.02000000'), ('ask', '11098.39'), ('open', 11867.35)])
high
last
timestamp
bid
vwap
volume
low
ask
open

In [12]:
def getBtc(value):
    res = requests.get('https://www.bitstamp.net/api/ticker_hour/')
    dev = res.json()
    return [*dev.values()]

In [13]:
print(type(dev))

#print(dev)
y = json.dumps(dev)
print(type(y))

pd.read_json(y, 'High', 'Last')

<class 'dict'>
<class 'str'>

high        1970-01-01 03:16:19.120000000
last        1970-01-01 03:15:48.850000000
timestamp   2019-06-30 08:08:34.000000000
bid         1970-01-01 03:15:39.120000000
vwap        1970-01-01 03:14:52.900000000
volume      1970-01-01 00:09:30.868499710
low         1970-01-01 03:13:36.650000000
ask         1970-01-01 03:15:48.850000000
open        1970-01-01 03:17:47.350000000
dtype: datetime64[ns]

Nueva columna diferencia de Px de apertura con el Px de cierre (hay que meterlo en otro archivo de funciones)

In [14]:
def PriceMov(p):
    dif = data_clean['Open'] - data_clean['Close']
    return dif


data_clean['Price diff'] = data_clean['Open', 'Close'].apply(PriceMov)

display(data_clean.head())

KeyError: ('Open', 'Close')

In [15]:
#el weighted puede que proporcione senyales de movimientes fuertes. 

display(data_clean.head())


#DataFrame.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')
    
    
    
#quiero detectar el volume low + strong movement

,Date,5min,Open,High,Low,Close,Volume (BTC),Volume (Currency),Weighted Price,diff
0,2019-06-03,00:00:00,8735.84,8745.96,8715.67,8715.74,15.77,137608.69,8724.77,20.10
1,2019-06-03,00:05:00,8715.74,8718.09,8691.93,8706.82,58.71,511301.42,8709.02,8.92
2,2019-06-03,00:10:00,8706.76,8708.93,8685,8685.00,54.75,476283.04,8699.47,21.76
3,2019-06-03,00:15:00,8686.16,8696,8671.47,8676.82,68.32,593057.25,8680.62,9.34
4,2019-06-03,00:20:00,8677.79,8695.56,8676.28,8691.24,11.44,99289.49,8682.81,13.45

In [142]:
low_variance = []

for col in data_clean._get_numeric_data():
    minimum = min(data_clean[col])
    ninety_perc = np.percentile(data_clean[col], 80)

In [ ]:
outliers = pd.DataFrame(columns=data.columns)

for col in stats.index:
    iqr = stats.at[col,'IQR']
    cutoff = iqr * 1.5
    lower = stats.at[col,'25%'] - cutoff
    upper = stats.at[col,'75%'] + cutoff
    results = data_clean[(data_clean[col] < lower) | 
                   (data_clean[col] > upper)].copy()
    results['Outlier'] = col
    outliers = outliers.append(results)

In [7]:
url = 'https://bitcoincharts.com/charts/bitstampUSD#rg1zig5-minztgSzm1g10zm2g25zi1gRSIzv'
res = req.get(url)
soup = BeautifulSoup(res.text, 'html.parser')
soup.find_all('tr')

[<tr><td class="label">Blocks</td><td>481823</td></tr>,
 <tr><td class="label">Total BTC</td><td>16.523M</td></tr>,
 <tr><td class="label">Difficulty</td><td>923233068449</td></tr>,
 <tr><td class="label">Estimated</td><td>887736944047 in 1 blks</td></tr>,
 <tr><td class="label">Network total</td><td>7983858.406 Thash/s</td></tr>,
 <tr><td class="label">Blocks/hour</td><td>7.25 / 497 s</td></tr>,
 <tr>
 <th>Timestamp</th><th>Open</th><th>High</th><th>Low</th><th>Close</th><th>Volume (BTC)</th><th>Volume (Currency)</th><th>Weighted Price</th>
 </tr>]